### ISSUE TITLE
ViewController `detail()` method change request

### ISSUE THREAD

**Issue by ScottMaxson** [nxus/web#16]
Can we change the `detail()` method to take the object in 3rd parameter (available at that point in `_detail` caller) instead of repeating the query? This looks like a cut&paste oversight maybe.

**Comment by loppear** [comment]
Intentional but possibly not helpful, to let the detail () perform
additional populate etc. But I win a prize for that original intent to
avoid re-querying in that case actually resulting in two queries everytime.
Overriding `findOne ` is probably the better approach for that.

Do you mind the asymmetry with list() taking a promised query still?

**Comment by ScottMaxson** [comment]
Good points ...
I might vote for having detail() receive the object, and list() receive a collection instead of the promised queries, and offer (as you suggest) over-rides for find() and findOne() instead. This de-couples the object-store access from the page-preparation steps, or at least it could. Some method re-naming, then, might be in order ... which could allow you to keep the old interface in place (if that's important -- I can live with changing the few places where I've used this).

**Comment by loppear** [comment]
I think this has been addressed for a while, in some combination of these ideas. current behavior is: `list` and `detail` receive promised queries analogously as the third param, and `_findOne` has been added to match `_find`.
